### ISSUE TITLE
Quick Add to Inbox

### ISSUE THREAD

**Issue by nicholascm** [arma7x/k-todoist#1]
Hi, thanks for making this app!

I was wondering if you'd accept the idea of a quick-add feature which drops a task directly to the todoist inbox?

**Comment by arma7x** [comment]
Put **Add Task** button on welcome screen ?

**Comment by nicholascm** [comment]
Yes. It takes a lot of clicks right now to get to where you can add a task, so if something comes up that you want to remember or record, it takes a while to be able to add it. 

Usually for using todoist, I add things to inbox and only later do I go back and put tasks into specific projects.

**Comment by arma7x** [comment]
Done https://github.com/arma7x/k-todoist/commit/b90291c2cbce740bb9494209a787e544fcdc45d1
Demo https://i.imgur.com/Z6900zt.png

**Comment by nicholascm** [comment]
Wow excellent! Thanks for doing that so fast! I can't wait to try it out!
